services:
  website:
    build:
      context: .
      dockerfile: Dockerfile.website
    container_name: go-website
    ports:
      - "8080:8080"
    environment:
      - TZ=UTC
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8080/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`localhost`)"
      - "traefik.http.services.website.loadbalancer.server.port=8080"

  nginx:
    image: nginx:alpine
    container_name: go-website-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - website
    restart: unless-stopped
    profiles:
      - production

networks:
  default:
    name: go-website-network
