<?php
// filepath: /home/lexi/source/github.com/0x800a6/website/src/utils/content.php

/**
 * Content retrieval utility
 * 
 * Provides functions to load and access processed content files
 * that were generated by the content processing script.
 */

class ContentManager {
    private static $instance = null;
    private $contentCache = [];
    private $contentDir;
    
    private function __construct() {
        $this->contentDir = dirname(__FILE__) . '/../content';
    }
    
    public static function getInstance() {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }
    
    /**
     * Get all content from the index
     */
    public function getIndex() {
        return $this->loadJson('index.json');
    }
    
    /**
     * Get a specific content item by path
     * 
     * @param string $path Content path (e.g., 'blog/2025/09/test')
     * @return array|null Content data or null if not found
     */
    public function getContent($path) {
        $index = $this->getIndex();
        return isset($index[$path]) ? $index[$path] : null;
    }
    
    /**
     * Get blog metadata
     */
    public function getBlogMeta() {
        return $this->loadJson('blog/meta.json');
    }
    
    /**
     * Get all blog posts
     */
    public function getBlogPosts() {
        $meta = $this->getBlogMeta();
        return isset($meta['posts']) ? $meta['posts'] : [];
    }
    
    /**
     * Get a specific blog post by slug
     * 
     * @param string $slug Blog post slug
     * @return array|null Blog post data or null if not found
     */
    public function getBlogPost($slug) {
        $posts = $this->getBlogPosts();
        foreach ($posts as $post) {
            if ($post['slug'] === $slug) {
                // Get the full content for this post
                $fullContent = $this->getContent($post['path']);
                return array_merge($post, $fullContent ?: []);
            }
        }
        return null;
    }
    
    /**
     * Get recent blog posts
     * 
     * @param int $limit Number of posts to return
     * @return array Recent blog posts
     */
    public function getRecentBlogPosts($limit = 5) {
        $posts = $this->getBlogPosts();
        return array_slice($posts, 0, $limit);
    }
    
    /**
     * Get blog posts by year
     * 
     * @param int $year Year to filter by
     * @return array Blog posts from the specified year
     */
    public function getBlogPostsByYear($year) {
        $posts = $this->getBlogPosts();
        return array_filter($posts, function($post) use ($year) {
            if (isset($post['date'])) {
                $postYear = date('Y', strtotime($post['date']));
                return $postYear == $year;
            }
            return false;
        });
    }
    
    /**
     * Search blog posts by title or content
     * 
     * @param string $query Search query
     * @return array Matching blog posts
     */
    public function searchBlogPosts($query) {
        $posts = $this->getBlogPosts();
        $query = strtolower($query);
        
        return array_filter($posts, function($post) use ($query) {
            $title = strtolower($post['title'] ?? '');
            $description = strtolower($post['description'] ?? '');
            
            return strpos($title, $query) !== false || 
                   strpos($description, $query) !== false;
        });
    }
    
    /**
     * Load and cache JSON file
     * 
     * @param string $filename Relative path to JSON file
     * @return array|null Decoded JSON data or null if file doesn't exist
     */
    private function loadJson($filename) {
        if (isset($this->contentCache[$filename])) {
            return $this->contentCache[$filename];
        }
        
        $filepath = $this->contentDir . '/' . $filename;
        
        if (!file_exists($filepath)) {
            return null;
        }
        
        $content = file_get_contents($filepath);
        $data = json_decode($content, true);
        
        if ($data === null) {
            error_log("Failed to decode JSON from: $filepath");
            return null;
        }
        
        $this->contentCache[$filename] = $data;
        return $data;
    }
    
    /**
     * Clear the content cache
     */
    public function clearCache() {
        $this->contentCache = [];
    }
}

/**
 * Convenience functions for global access
 */

/**
 * Get the content manager instance
 */
function content() {
    return ContentManager::getInstance();
}

/**
 * Get a specific content item
 */
function get_content($path) {
    return content()->getContent($path);
}

/**
 * Get blog posts
 */
function get_blog_posts($limit = null) {
    $posts = content()->getBlogPosts();
    return $limit ? array_slice($posts, 0, $limit) : $posts;
}

/**
 * Get a specific blog post
 */
function get_blog_post($slug) {
    return content()->getBlogPost($slug);
}


/**
 * Get recent blog posts
 */
function get_recent_blog_posts($limit = 5) {
    return content()->getRecentBlogPosts($limit);
}

/**
 * Search blog posts
 */
function search_blog_posts($query) {
    return content()->searchBlogPosts($query);
}